knp_paginator:
    page_range: 5                      # Nombre de pages affichées dans la pagination
    default_options:
        page_name: page                # Nom de la variable de requête utilisée pour la pagination
        sort_field_name: sort          # Nom de la variable de requête utilisée pour le tri
        sort_direction_name: direction # Nom de la variable de requête utilisée pour la direction de tri
        distinct: true  