framework:
    mailer:
        dsn: 'smtp://smtp.gmail.com?port=587&encryption=tls&auth_mode=login&username=recycle.tunisia&password=ztntffukvpwraygm'
        envelope:
            sender: 'recycle.tunisia@gmail.com'
        

                 # Or you can use the following format:
        # smtp:
        #     host: smtp.gmail.com
        #     port: 587
        #     encryption: tls
        #     auth_mode: login
        #     username: your_gmail_username
        #     password: your_gmail_password